### PR TITLE
640 number_to_scaled_string is duplicated in several commands

### PR DESCRIPTION
**Pull request by jasonbking**
Having had some resource constraints on my OmniOS vm that's preventing the running of all of the zfs tests on it, per Matt Ahrens's suggestion, creating the PR here to run the ZFS tests to ensure this doesn't cause a problem with any of the tests.

### CODE REVIEW

**Comment by prakashsurya** [comment]
@jasonbking can you rebase (e.g. using `git rebase`) or merge (e.g. using `git merge`) these patches with the openzfs codebase? we maintain a `jenkins` directory in the openzfs repository that doesn't exist in illumos-gate, and the lack of that directory is causing the build/test failure.

I can give more details on exactly how to do that, if it's not clear to you; just let me know. Thanks; and sorry for the confusion.

**Comment by jasonbking** [comment]
I've rebased it off openzfs/master and pushed it back to my fork (had to push -f though) -- though I'm not sure what needs to happen (if anything) for the PR to update (or if I'd need to just create a new one).

**Comment by yuripv** [comment]
@jasonbking that's exactly what you had to do, no need for new PR.

**Comment by jasonbking** [comment]
The output is somewhat confusing -- it suggests there are a number of tests that are passing that it expected it not to pass??  Does that mean all of those are a problem?
There does look to be one test that's failing - FAIL largest_pool/largest_pool_001_pos (expected PASS)
 -- but I cannot find any way to get more detailed output on it to understand why it's failing.  Any suggestions?

**Comment by prakashsurya** [comment]
generally, I only worry about the tests listed in the last section; i.e.
```
Tests with results other than PASS that are unexpected:
    FAIL largest_pool/largest_pool_001_pos (expected PASS)
```
if there's any tests listed here, it'll cause the test to report a failure; the other sections are largely ignored (let me know if you'd like more explanation of the different sections, I'll don't want to provide too much info unless you're actually interested in it).

so, it looks as though this test run failed the `largest_pool/largest_pool_001_pos` test case. the source for that test can be seen [here](https://github.com/openzfs/openzfs/blob/master/usr/src/test/zfs-tests/tests/functional/largest_pool/largest_pool_001_pos.ksh), and the output of that test can be seen [here](http://jenkins.open-zfs.org/job/openzfs/job/openzfs/job/PR-435/2/artifact/run-zfs-tests.log).

Unfortunately I can't link directly to the section of that log file related to this test, so I use my browser's search functionality and the test's name (i.e. "largest_pool_001_pos"), and it'll jump to the specific section. I copy/pasted it below too:
```
Test: /opt/zfs-tests/tests/functional/largest_pool/largest_pool_001_pos (run as root) [00:08] [FAIL]
22:35:20.89 ASSERTION: The largest pool can be created and a dataset in that pool can be created and mounted.
22:35:20.89 NOTE: Create a pool which will contain a volume device
22:35:21.25 SUCCESS: zpool create -f testpool2 c4t1d0 c4t2d0 c4t3d0
22:35:21.25 NOTE: Create a volume device of desired sizes: 2pb
22:35:21.30 NOTE: Create the largest pool allowed using the volume vdev
22:35:21.62 SUCCESS: zpool create -f testpool /dev/zvol/dsk/testpool2/testvol600549
22:35:21.62 NOTE: Create a zfs file system in the largest pool
22:35:21.69 SUCCESS: zfs create testpool/testfs
22:35:21.69 NOTE: Parse the execution result
22:35:21.69 NOTE: Detect zpool testpool in this test machine.
22:35:21.70 SUCCESS: eval zpool list testpool > /tmp/j.600549
22:35:21.71 testpool  1.98P   872K  1.98P         -     0%     0%  1.00x  ONLINE  -
22:35:21.72 SUCCESS: eval grep testpool /tmp/j.600549 | 		awk '{print }' | grep P
22:35:21.72 NOTE: Detect the file system in this test machine.
22:35:22.28 SUCCESS: eval df -F zfs -h > /tmp/j.600549
22:35:22.28 testpool              1.92P   176K      1.92P     1%    /testpool
22:35:22.28 testpool/testfs       1.92P   176K      1.92P     1%    /testpool/testfs
22:35:22.29 SUCCESS: eval grep testpool /tmp/j.600549 | 		awk '{print }' | grep P
22:35:22.29 NOTE: unmount this zfs file system testpool/testfs
22:35:22.30 SUCCESS: zfs unmount testpool/testfs
22:35:22.30 NOTE: Destroy zfs, volume & zpool
22:35:22.41 SUCCESS: zfs destroy testpool/testfs
22:35:22.80 SUCCESS: zfs destroy testpool2/testvol600549
22:35:23.01 NOTE: Create a pool which will contain a volume device
22:35:23.28 SUCCESS: zpool create -f testpool2 c4t1d0 c4t2d0 c4t3d0
22:35:23.28 NOTE: Create a volume device of desired sizes: 5pb
22:35:23.31 NOTE: Create the largest pool allowed using the volume vdev
22:35:23.66 SUCCESS: zpool create -f testpool /dev/zvol/dsk/testpool2/testvol600549
22:35:23.66 NOTE: Create a zfs file system in the largest pool
22:35:23.73 SUCCESS: zfs create testpool/testfs
22:35:23.73 NOTE: Parse the execution result
22:35:23.74 NOTE: Detect zpool testpool in this test machine.
22:35:23.75 SUCCESS: eval zpool list testpool > /tmp/j.600549
22:35:23.75 testpool  4.97P   872K  4.97P         -     0%     0%  1.00x  ONLINE  -
22:35:23.76 SUCCESS: eval grep testpool /tmp/j.600549 | 		awk '{print }' | grep P
22:35:23.76 NOTE: Detect the file system in this test machine.
22:35:23.77 SUCCESS: eval df -F zfs -h > /tmp/j.600549
22:35:23.78 testpool              4.81P   176K      4.81P     1%    /testpool
22:35:23.78 testpool/testfs       4.81P   176K      4.81P     1%    /testpool/testfs
22:35:23.79 SUCCESS: eval grep testpool /tmp/j.600549 | 		awk '{print }' | grep P
22:35:23.79 NOTE: unmount this zfs file system testpool/testfs
22:35:23.80 SUCCESS: zfs unmount testpool/testfs
22:35:23.80 NOTE: Destroy zfs, volume & zpool
22:35:23.93 SUCCESS: zfs destroy testpool/testfs
22:35:24.31 SUCCESS: zfs destroy testpool2/testvol600549
22:35:24.77 NOTE: Create a pool which will contain a volume device
22:35:25.05 SUCCESS: zpool create -f testpool2 c4t1d0 c4t2d0 c4t3d0
22:35:25.05 NOTE: Create a volume device of desired sizes: 10pb
22:35:25.09 NOTE: Create the largest pool allowed using the volume vdev
22:35:25.49 SUCCESS: zpool create -f testpool /dev/zvol/dsk/testpool2/testvol600549
22:35:25.50 NOTE: Create a zfs file system in the largest pool
22:35:25.59 SUCCESS: zfs create testpool/testfs
22:35:25.59 NOTE: Parse the execution result
22:35:25.60 NOTE: Detect zpool testpool in this test machine.
22:35:25.61 SUCCESS: eval zpool list testpool > /tmp/j.600549
22:35:25.62 testpool  9.94P   872K  9.94P         -     0%     0%  1.00x  ONLINE  -
22:35:25.62 SUCCESS: eval grep testpool /tmp/j.600549 | 		awk '{print }' | grep P
22:35:25.62 NOTE: Detect the file system in this test machine.
22:35:25.64 SUCCESS: eval df -F zfs -h > /tmp/j.600549
22:35:25.64 testpool              9.63P   176K      9.63P     1%    /testpool
22:35:25.64 testpool/testfs       9.63P   176K      9.63P     1%    /testpool/testfs
22:35:25.65 SUCCESS: eval grep testpool /tmp/j.600549 | 		awk '{print }' | grep P
22:35:25.65 NOTE: unmount this zfs file system testpool/testfs
22:35:25.66 SUCCESS: zfs unmount testpool/testfs
22:35:25.66 NOTE: Destroy zfs, volume & zpool
22:35:25.79 SUCCESS: zfs destroy testpool/testfs
22:35:26.17 SUCCESS: zfs destroy testpool2/testvol600549
22:35:26.40 NOTE: Create a pool which will contain a volume device
22:35:26.71 SUCCESS: zpool create -f testpool2 c4t1d0 c4t2d0 c4t3d0
22:35:26.71 NOTE: Create a volume device of desired sizes: 2eb
22:35:26.74 NOTE: Create the largest pool allowed using the volume vdev
22:35:27.10 SUCCESS: zpool create -f testpool /dev/zvol/dsk/testpool2/testvol600549
22:35:27.10 NOTE: Create a zfs file system in the largest pool
22:35:27.17 SUCCESS: zfs create testpool/testfs
22:35:27.17 NOTE: Parse the execution result
22:35:27.18 NOTE: Detect zpool testpool in this test machine.
22:35:27.19 SUCCESS: eval zpool list testpool > /tmp/j.600549
22:35:27.19 testpool  <overflow>   872K  <overflow>         -     0%     0%  1.00x  ONLINE  -
22:35:27.20 SUCCESS: eval grep testpool /tmp/j.600549 | 		awk '{print }' | grep E
22:35:27.20 NOTE: Detect the file system in this test machine.
22:35:27.22 SUCCESS: eval df -F zfs -h > /tmp/j.600549
22:35:27.23 
22:35:27.23 ERROR: eval grep testpool /tmp/j.600549 | 		awk '{print }' | grep E exited 1
```

I hope that helps. I didn't look into _why_ the test is failing, but let me know if you need some help with that. Superficially, it looks like `grep` failed (i.e. reported a non-zero exit code), but I can't immediately tell why it would have failed.

**Comment by ahrens** [comment]
```
22:35:27.19 testpool  <overflow>   872K  <overflow>         -     0%     0%  1.00x  ONLINE  -
```
That seems like a change in behavior that you'll need to investigate.  IIRC, the zfs_nicenum() just takes a uint64_t, so it shouldn't be possible for it to overflow.

**Comment by jasonbking** [comment]
Hmm.. some reason my original comment didn't get posted.  I found the error, I just need to figure out what the values were that triggered the overflow (I'll dig into the test itself this afternoon and see what I can figure out on that).

I suspect what might be happening is that the output buffer is too small (assuming no other bugs).  Such an instance will also generate an overflow error -- the libzfs version will truncate (and libzpool and zdb will just overrun).  The thought being that truncation will produce incorrect output, and better to be explicit vs. confuse or mislead.

**Comment by ahrens** [comment]
```
22:35:26.71 NOTE: Create a volume device of desired sizes: 2eb
```
I don't think the output 
buffer is too small, and if it is, substituting the longer string `<overflow>` wouldn't be the right solution :-)

It looks like it's trying to create a 2EB pool, and your code is handling up to `E`, so it should still fit into the 5 characters available.  The largest possible value (2^64) is 16EB, which should also fit into 5 characters.

**Comment by jasonbking** [comment]
I think I figured it out -- since some consumers want the scaling to be powers of 10 instead of 2, it checks if the next largest suffix is larger than the value to scale to determine the correct suffix.  So for exabyte values, it tries to see if the value to scale is smaller than a (somewhat ironically) zetabyte, which cannot fit in a 64-bit integer.  I'll push an update with the fix in a few minutes to verify (I've recreated & tested it locally, but just to be sure).

**Comment by ahrens** [comment]
integrated directly to illumos.

**Pull request closed without merging**
