### PR TITLE
6637 replacing "dontclose" with "should_close"

### PR DESCRIPTION
**Pull request by res1233**
I find that this is a lot easier to read. "not don't close" is somewhat tough on the eyes.

### CODE REVIEW

**Comment by ahrens** [comment]
@zettabot go

**Comment by ahrens** [comment]
Changes look good.  Can you please open an illumos bug and change the commit message to the bug id + synopsis?  For details see https://github.com/openzfs/openzfs/blob/master/README.md

**Comment by ahrens** [comment]
@zettabot go

**Comment by prakashsurya** [comment]
:+1: LGTM. I agree, constructs like that always confuse me.

**Pull request closed without merging**
