### PR TITLE
7582 vmxnet3s MAC callbacks erroneously return DDI_ return values

### PR DESCRIPTION
**Pull request by dankimmel**
7583 vmxnet3s rx buffer allocations can result in system unresponsiveness

Reviewed by: Pavel Zakharov <pavel.zakharov@delphix.com>
Reviewed by: Matthew Ahrens <mahrens@delphix.com>
Reviewed by: Steve Gonczi <steve.gonczi@delphix.com>

Note: this diff depends on https://github.com/openzfs/openzfs/pull/238 merging first. If you are reviewing the code, make sure you just look at the second commit in this PR (the first commit is a duplicate of the other PR).

Device callbacks for the MAC module are expected to return 0 for
success, and a positive non-zero error code (errno) on failure.
The vmxnet3s driver's MAC callbacks currently only return
DDI_SUCCESS or DDI_FAILURE. The fact that DDI_SUCCESS is 0 is a
happy and harmless coincidence, but the lack of error codes could
be problematic for diagnostic purposes.

Also, we've had a number of customer problems related to vmxnet3s
devices becoming unreachable over the network. The commonalities in
these cases have been that a vmxnet3 device has jumbo frames enabled,
and as receive throughput goes up for some sustained period, vmxnet3s
memory allocations start taking a very long time in interrupt context
and ultimately failing.

The issue is that vmxnet3s has a fixed-size receive buffer pool of
pre-allocated buffers into which incoming packets are copied. When
all of those buffers have been used (i.e., all buffers are used for
in-flight data being processed by the networking stack), vmxnet3s
starts dynamically allocating memory as needed. It requires
contiguous pages for dma of the size of the MTU. For 1500 byte MTU,
that's only a single page allocation. For 9000 byte MTU (jumbo
frames), that's 3 contiguous pages. When memory gets fragmented
enough, these allocations can take a very long time and ultimately
fail.

vmxnet3s is doing contiguous multi-page allocations in interrupt
context, and these allocations can take a long time (many seconds).
We should avoid doing these allocations altogether by doing the
following:

1) Pre-allocating the maximum number of buffers in the buffer pool
   so that we never have to allocate memory in interrupt context.
2) Increase the size of the buffer pool to increase the likelihood
   that a pre-allocated buffer will be available even under very
   heavy load.
3) In the event that a receive interrupt comes in and there are no
   available buffers in the pool, instead of dynamically allocating
   a new buffer, we drop the packet.

Upstream bugs: DLPX-43759, DLPX-47119

### CODE REVIEW

**Comment by dankimmel** [comment]
@zettabot go

**Comment by danmcd** [comment]
Yes, thanks for extracting this separately, and I'm satisfied.

**Comment by dankimmel** [comment]
The ztest failure in `dmu_tx_willuse_space` is a known (and obviously unrelated) bug. Marking this as `test pass`.

**Comment by dankimmel** [comment]
@ahrens This one is good to go, but depends on https://github.com/openzfs/openzfs/pull/238 being integrated first. When you merge make sure you don't accidentally pull in the first commit here twice.

**Pull request closed without merging**
