### PR TITLE
6401 run.py should reopen files if they encounter transient I/O errors

### PR DESCRIPTION
**Pull request by wca**
See illumos #6401 for additional comments.

### CODE REVIEW

**Comment by ahrens** [comment]
@jwk404 can you take a look?

**Comment by jwk404** [comment]
That makes sense, thanks. We're not seeing the same behavior because /var is in the root filesystem.

**Comment by wca** [comment]
I've updated/force-pushed the commit to include the required import.

**Comment by ahrens** [comment]
@zettabot go

**Comment by wca** [comment]
I would assert that ztest failures can't possibly be caused by this change.

**Comment by ahrens** [comment]
@wca I agree, tests look good

**Pull request closed without merging**
