### PR TITLE
7103 failed test cli_root/zfs_snapshot/zfs_snapshot_009_pos

### PR DESCRIPTION
**Pull request by ikozhukhov**

### CODE REVIEW

**Comment by jwk404** [comment]
This bug is more subtle than an off by one error. The problem is that the hard coded number (209, 210) makes assumptions about the other components of the dataset name. What this means is that on DEBUG kernels we might be testing the maximum length of a dataset name, but not on non-DEBUG because the pool names include the pid. The correct solution here is to get the length of the non-repeating portion of the name, subtract it from the max, and use that for the repeating 'x' padding.

**Comment by ikozhukhov** [comment]
i have tested it on non-DEBUG build and test failed.
i'll investigate it and provide another solution for review.
thanks for your review and details.

**Comment by ahrens** [comment]
@zettabot go

**Comment by ikozhukhov** [comment]
well, i have tested this test on non-DEBUG build and it failed. i'd like propose: integrate this fix as is, because we are using DEBUG builds for testing, and probably add a comment to this test about need additional work on non-DEBUG build.
what do you think about it?

**Comment by jwk404** [comment]
I think it's preferable to wait until the fix works for both DEBUG and non-DEBUG systems. We shouldn't knowingly push changes with test failures.

**Comment by ikozhukhov** [comment]
i have tested latest build based on smartos and my zfs tests updates - i have no issues with this test on debug and non-debug builds - i mean, with my changes in this test

**Comment by ahrens** [comment]
We're going to go with the alternate fix proposed here: http://cr.illumos.org/~webrev/marcel/il-7103-zfs_snapshot_009_pos/

**Pull request closed without merging**
