### PR TITLE
5778 nvpair_type_is_array() does not recognize DATA_TYPE_INT8_ARRAY

### PR DESCRIPTION
**Pull request by avg-I**
Tested using a trivial program.

### CODE REVIEW

**Comment by ahrens** [comment]
@zettabot go

**Comment by ahrens** [comment]
Changes look good to me.

**Comment by prakashsurya** [comment]
LGTM!

**Comment by prakashsurya** [comment]
@avg-I do you think the "trivial program" you used to test this change would be useful to incorporate into the test suite?

**Pull request closed without merging**
