### PR TITLE
8544 libzfs namespace needs proper locking

### PR DESCRIPTION
**Pull request by yuripv**
Introduce proper locking for the libzfs namespace access.

### CODE REVIEW

**Comment by andy-js** [comment]
LGTM.

**Comment by yuripv** [comment]
I don't think the failed test case is related to this change, running the utils_test section locally passes all tests:
```
$ sudo rm -rf /var/tmp/test_results/ && /opt/zfs-tests/bin/zfstest -ac utils.run
Test: /opt/zfs-tests/tests/functional/utils_test/setup (run as root) [00:05] [PASS]
Test: /opt/zfs-tests/tests/functional/utils_test/utils_test_001_pos (run as root) [00:00] [PASS]
Test: /opt/zfs-tests/tests/functional/utils_test/utils_test_002_pos (run as root) [00:00] [PASS]
Test: /opt/zfs-tests/tests/functional/utils_test/utils_test_003_pos (run as root) [00:00] [PASS]
Test: /opt/zfs-tests/tests/functional/utils_test/utils_test_004_pos (run as root) [00:00] [PASS]
Test: /opt/zfs-tests/tests/functional/utils_test/utils_test_005_pos (run as root) [00:00] [PASS]
Test: /opt/zfs-tests/tests/functional/utils_test/utils_test_006_pos (run as root) [00:00] [PASS]
Test: /opt/zfs-tests/tests/functional/utils_test/utils_test_007_pos (run as root) [00:00] [PASS]
Test: /opt/zfs-tests/tests/functional/utils_test/utils_test_008_pos (run as root) [00:00] [PASS]
Test: /opt/zfs-tests/tests/functional/utils_test/utils_test_009_pos (run as root) [00:00] [PASS]
Test: /opt/zfs-tests/tests/functional/utils_test/cleanup (run as root) [00:00] [PASS]
```

**Comment by ahrens** [comment]
libzfs is generally MT-unsafe.  If these two threads are using the same libzfs_handle_t, things are going to go badly for many reasons, not just due to concurrent manipulation of libzfs_ns_avl.  What's the rationale for adding locking to only this one part of libzfs?

**Comment by yuripv** [comment]
This is the one we have been hitting with syseventd, so instead of rewriting large parts syseventd's zfs_mod I choose to at least try to make libzfs a bit more MT-aware.

**Comment by idodeclare** [comment]
W.r.t. these changes, if a racing thread did not acquire a write lock through rw_trywrlock, then were any error to occur for the active writer, it seems the waiting reader is uninformed and goes on its way as though libzfs_ns_avl is ready to use.

(As an aside regarding the pre-existing code, I wonder whether libzfs_ns_gen is not perhaps set too early given all the errors that may occur subsequently in namespace_reload().)

**Comment by yuripv** [comment]
Yes, you are right, probably it should be easier to just fix the syseventd.  Closing.

**Pull request closed without merging**
