### PR TITLE
7304 zfs filesystem/snapshot counts should be read-only

### PR DESCRIPTION
**Pull request by jjelinek**
Submitting this pull request to trigger a zfs test run.

### CODE REVIEW

**Comment by dankimmel** [comment]
@zettabot go

**Comment by rmustacc** [comment]
@dankimmel Can you confirm that we're good here from a zfs testing perspective? The change was previously reviewed, but we wanted to make sure we're good from an RTI perspective.

**Comment by ahrens** [comment]
Test results look great.

**Comment by rmustacc** [comment]
Thanks Matt!

**Comment by ahrens** [comment]
pushed to illumos:
commit 007a6c1f69652d7e3f2d2012a9332221d430491b
Author: Jerry Jelinek <jerry.jelinek@joyent.com>
Date:   Wed Aug 17 22:08:39 2016 +0000

    7304 zfs filesystem/snapshot counts should be read-only
    Reviewed by: Garrett D'Amore <garrett@damore.org>
    Reviewed by: Matthew Ahrens <mahrens@delphix.com>
    Approved by: Dan McDonald <danmcd@omniti.com>

**Pull request closed without merging**
