### PR TITLE
Trying again with sequential scan -- this is simply

### PR DESCRIPTION
**Pull request by kithrup**
rereating the branch, after resyncing with master, and
reapplying the diffs.

### CODE REVIEW

**Comment by ikozhukhov** [comment]
https://bitbucket.org/dilos/dilos-illumos/commits/d6cc4eed5a5720864f0d91f5c278d5bed3f55815
proposed lint fixes

**Comment by ikozhukhov** [comment]
could you push your update with -f again - we have no build issues, but on tests VM lost connection
update will initiate build + test peocess

**Comment by ikozhukhov** [comment]
what is progress?
i tried to test it and have issues with some panic too with the same as with zfs tests.
ideas - how to try to fix it?

**Comment by kithrup** [comment]
On Jun 15, 2018, at 4:19 AM, Igor K <notifications@github.com> wrote:
> 
> what is progress?
> i tried to test it and have issues with some panic too with the same as with zfs tests.
> ideas - how to try to fix it?

I’ve still not been able to reproduce it under FreeBSD, so I’m not sure what’s
going on with it.

I could try undoing the last patch I added to it (https://github.com/zfsonlinux/zfs/commit/a8b2e30685c9214c),
since that’s the least tested part.  But that’s all I can think of right now.

Sean.

**Comment by ahrens** [comment]
This is another version of porting the FreeBSD version of this to illumos: https://www.illumos.org/rb/r/1226/

**Comment by tsoome** [comment]
> This is another version of porting the FreeBSD version of this to illumos: https://www.illumos.org/rb/r/1226/

Note it does depend on 2 other commits:

https://www.illumos.org/rb/r/1224/
and
https://www.illumos.org/rb/r/1225/

The bundle itself seems to be stable enough to run resilver on mirror, raidz and scrubs. The only down side is that I did skip some ztest scripts, but it should be easy task to bring them up.

**Pull request closed without merging**
