### PR TITLE
Merge

### PR DESCRIPTION
**Pull request by ikozhukhov**

### CODE REVIEW

**Comment by prakashsurya** [comment]
@zettabot go

**Comment by dankimmel** [comment]
@zettabot go

**Comment by ikozhukhov** [comment]
please @zettabot go again - branch was updated

**Comment by ahrens** [comment]
@zettabot go

**Comment by ikozhukhov** [comment]
@ahrens : it is green, but wants Update branch again?

**Comment by prakashsurya** [comment]
@ikozhukhov I think that is because a commit landed on the openzfs master branch since you branched to do the merge of illumos:
```
$ git log --decorate --oneline --graph origin/pr/240..origin/master
* d1421ac (origin/master, origin/HEAD) 7570 tunable to allow zvol SCSI unmap to return on commit of txn to ZIL
```

**Comment by ikozhukhov** [comment]
please @zettabot go

**Comment by ahrens** [comment]
@zettabot go

**Comment by ikozhukhov** [comment]
@ahrens : we are green, you can merge it :)

**Pull request merged**
