### PR TITLE
7614 zfs device evacuation/removal

### PR DESCRIPTION
**Pull request by ahrens**
Reviewed by: Alex Reece <alex@delphix.com>
Reviewed by: George Wilson <george.wilson@delphix.com>
Reviewed by: John Kennedy <john.kennedy@delphix.com>
Reviewed by: Prakash Surya <prakash.surya@delphix.com>

This project allows top-level vdevs to be removed from the storage pool
with “zpool remove”, reducing the total amount of storage in the pool.
This operation copies all allocated regions of the device to be removed
onto other devices, recording the mapping from old to new location.
After the removal is complete, read and free operations to the removed
(now “indirect”) vdev must be remapped and performed at the new location
on disk.  The indirect mapping table is kept in memory whenever the pool
is loaded, so there is minimal performance overhead when doing
operations on the indirect vdev.

The size of the in-memory mapping table will be reduced when its entries
become “obsolete” because they are no longer used by any block pointers
in the pool.  An entry becomes obsolete when all the blocks that use it
are freed.  An entry can also become obsolete when all the snapshots
that reference it are deleted, and the block pointers that reference it
have been “remapped” in all filesystems/zvols (and clones).  Whenever an
indirect block is written, all the block pointers in it will be
“remapped” to their new (concrete) locations if possible.  This process
can be accelerated by using the “zfs remap” command to proactively
rewrite all indirect blocks that reference indirect (removed) vdevs.

Note that when a device is removed, we do not verify the checksum of the
data that is copied.  This makes the process much faster, but if it were
used on redundant vdevs (i.e. mirror or raidz vdevs), it would be
possible to copy the wrong data, when we have the correct data on e.g.
the other side of the mirror.  Therefore, mirror and raidz devices can
not be removed.

### CODE REVIEW

**Comment by ahrens** [comment]
@zettabot go

**Comment by ahrens** [comment]
@zettabot go

**Comment by ahrens** [comment]
@zettabot go

**Comment by ahrens** [comment]
@zettabot go

**Comment by jimklimov** [comment]
Nice news. :+1: 

In our pocket of the IRC-verse, we decided that the last sentence limits the use of this new wonderful feature to containing (or amending) those "Oh, crap!" moments when people mistake a `zpool add disk` vs. `zpool attach disk` - which indeed is a major source of worry whenever one does one of these operations?

Are there plans to enable the feature for other VDEV types, perhaps in a later PR and learning eventually some lessons from this one?

**Comment by ahrens** [comment]
@jimklimov 
> Are there plans to enable the feature for other VDEV types, perhaps in a later PR and learning eventually some lessons from this one?

I don't have any plans to do so, but I would welcome effort along those lines.

**Comment by ahrens** [comment]
@zettabot go

**Comment by ahrens** [comment]
@zettabot go

**Comment by ahrens** [comment]
@zettabot go

**Comment by ahrens** [comment]
@zettabot go

**Comment by galindro** [comment]
@ahrens when you expect to merge this PR in master and release a new version with this great feature?

**Comment by ahrens** [comment]
@galindro I've been working on getting this rebased onto master, which is now completed.  I'm hoping to get it merged sometime in July.

**Comment by galindro** [comment]
Nice.
 tks @ahrens

**Comment by ahrens** [comment]
@gmelikov I was wondering if you'd be interested in porting this to Linux before we integrate it to illumos.  It would be great to get additional feedback on this change, and we might attract more attention on ZoL.

**Comment by gmelikov** [comment]
@ahrens I'm afraid I won't have much time to do it quickly now, but i've already began, sooner or later we'll port it.

**Comment by gmelikov** [comment]
@ahrens unfortunately I did't have enough time this summer to port it due to unexpected load at work, I'm very sorry that I misled you.

**Comment by ahrens** [comment]
@gmelikov no worries.

**Comment by ikozhukhov** [comment]
hey, when we can see it integrated? :)

**Comment by ahrens** [comment]
@ikozhukhov: @prashks is working on adding support for removing mirror devices.  He's almost done and we hope to have the review updated by the OpenZFS DevSummit later this month.

**Comment by ahrens** [comment]
superseded by https://github.com/openzfs/openzfs/pull/482

**Pull request closed without merging**
