### PR TITLE
8264 want support for promoting datasets in libzfs_core

### PR DESCRIPTION
**Pull request by andy-js**

### CODE REVIEW

**Comment by avg-I** [comment]
LGTM, thank you!

**Comment by avg-I** [comment]
Looks like you need to rebase on the latest master, though.

**Comment by prakashsurya** [comment]
@andy-js can you rebase this onto the latest master branch? that'll fix the build.

**Comment by andy-js** [comment]
Thanks for the review Andriy.

Please see #389 which is rebased on the latest mater branch.

**Pull request closed without merging**
