### PR TITLE
6562 Refquota on receive doesn't account for overage.

### PR DESCRIPTION
**Pull request by danmcd**
I'd appreciate @zettabot taking a crack at this.

### CODE REVIEW

**Comment by ahrens** [comment]
@zettabot go

**Comment by danmcd** [comment]
Did Zettabot get kicked off?

**Comment by ahrens** [comment]
@zettabot go

**Comment by danmcd** [comment]
Hmmm... I saw this:

```
failed: /usr/bin/python /usr/local/zfstest-report.py results.txt
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

What happened?

**Comment by yuripankov** [comment]
@danmcd:

Tests with results other than PASS that are unexpected:
    FAIL zvol/zvol_swap/zvol_swap_006_pos (expected PASS)

Don't think it's related to your changes, but anyway...

**Comment by danmcd** [comment]
Can I get another go at zettabot?

**Comment by ahrens** [comment]
@zettabot go

**Comment by danmcd** [comment]
Nice!  And receive_012 is in the output as well.  I think I'll RTI once I get back from FOSDEM.

**Comment by danmcd** [comment]
Any reviewers here besides @ahrens want to take a look?  I've also asked on the mailing lists.  I'm 1-2 reviewers away from RTI.  (And this got included in an OmniOS update today already.)

**Comment by danmcd** [comment]
Again, ping for reviewers?

**Comment by ahrens** [comment]
Pushed to illumos.

**Pull request closed without merging**
