### PR TITLE
7290 ZFS test suite needs to control what utilities it can run

### PR DESCRIPTION
**Pull request by jwk404**
Reviewed by: Dan Kimmel dan.kimmel@delphix.com
Reviewed by: Matthew Ahrens mahrens@delphix.com

### CODE REVIEW

**Comment by danmcd** [comment]
If folks want a webrev, check here:  http://kebe.com/~danmcd/webrevs/7290/

**Comment by dankimmel** [comment]
@jwk404, do you want to add the details from your internal review explaining the parts of this that are interesting to look at? Otherwise I'm guessing folks might not be able to digest it.

**Comment by jwk404** [comment]
The vast majority of files here have changes that consist only of a) updated copyright and b) substitutions like $SED -> sed. Below is a list of files with additional changes:

* usr/src/test/zfs-tests/cmd/scripts/zfstest.ksh
Added functionality to create symlinks for desired utilities and constrain path before test execution.

* usr/src/test/zfs-tests/include/commands.cfg
This is now a list of utilities (one per system directory) that the suite is allowed to use. The list is used during the creation of the symlinks mentioned above.

* usr/src/test/zfs-tests/include/default.cfg
Removed a set of variables similar to those that were in commands.cfg

We've been running with these changes at Delphix for a week or so.

**Comment by danmcd** [comment]
Glanced over the $CMD -> cmd changes, and did not see anything objectionable.  The path-constraining logic and the cleanups in the three specified files above also seem alright.  There's a pre-existing packaging dependency condition I see thanks to these being reorganized (requirement of GNU utilties for gnu dd(1)), but that's not a blocker for THIS bug.

Ship it.

**Comment by dankimmel** [comment]
@zettabot go

**Comment by dankimmel** [comment]
@jwk404 and I looked at the `zfs-test` failures above: all are known issues except for `rootpool_007_neg`, which looks like a new test bug but is unrelated to this diff. He will file a bug to track that one.

**Comment by ahrens** [comment]
@zettabot go

**Comment by jwk404** [comment]
@zettabot go

**Comment by jwk404** [comment]
Test machine panicked during tests due to https://www.illumos.org/issues/7146

**Comment by jwk404** [comment]
@zettabot go

**Comment by jwk404** [comment]
@zettabot go

**Comment by jwk404** [comment]
The zloop failure is unrelated to these test changes. This change is ready to be pushed.

**Pull request closed without merging**
