### PR TITLE
Don't allow "." or ".." as dataset names. It really does not great

### PR DESCRIPTION
**Pull request by kithrup**
things. Especially if your pool is mounted in /

### CODE REVIEW

**Comment by behlendorf** [comment]
Agreed!  A similar fix was applied to ZoL here https://github.com/zfsonlinux/zfs/pull/8842 which you may want to consider as an alternative fix; https://github.com/zfsonlinux/zfs/commit/9c7da9a95aaaecced0a1cfc40190906e7a691327

**Comment by kithrup** [comment]
Oh yes, that does it.  (It seems to handle the delimiter case different, but I think that's ok -- you cant create a snapshot of a dataset that doesn't exist.)  Let me see how well I can just cherry-pick it.

**Comment by dcarosone** [comment]
Is there a similar issue for naming snapshots, given their visibility in
the .zfs/snapshots/ meta directory?

**Comment by kithrup** [comment]
Github hasn't been liking me.  I push-forced a cherry-pick of the above commit.

**Pull request closed without merging**
