### PR TITLE
Merge remote-tracking branch 'illumos/master' into illumos-sync

### PR DESCRIPTION
**Pull request by zettabot**

### CODE REVIEW

**Comment by ahrens** [comment]
@zettabot go

**Comment by prakashsurya** [comment]
@zettabot go

**Comment by prakashsurya** [comment]
I think the build is broken on illumos; here's the log for the build of this PR: http://us-east.manta.joyent.com/zettabot/public/openzfs/openzfs/pull/299/1/03-build.html

I've kicked off the tests again since I've made some small tweaks to the build automation earlier today, but I have no reason to believe the build will work this second time.

@danmcd we're building on OmniOS r151020 and I noticed you sent an email about needed an updated version of GCC when building illumos on that platform; is this the failure mode we'd see without the updated GCC?

**Comment by rmustacc** [comment]
@prakashsurya Yes, it is.

**Comment by prakashsurya** [comment]
Perfect; thanks for the confirmation! I'll figure out what's needed to update our build environment to get past this.

**Comment by prakashsurya** [comment]
Actually, looking a little closer, I think this run _should_ work; Dan's mail to the illumos list says the new package was pushed, and I see that version picked up in this latest build:
```
root@omnios:/root# pkg list -v gcc44
FMRI                                                                         IFO
pkg://omnios/developer/gcc44@4.4.4-0.151020:20170209T164037Z                 i--
```

**Comment by danmcd** [comment]
Latest illumos-gate build just fine on r151020 with the new gcc44 compiler, as did illumos-omnios:r151020 (so old bits work too).

**Comment by danmcd** [comment]
Same with r151014, both -gate, and -omnios:r151014.

**Comment by prakashsurya** [comment]
@danmcd sorry for the noise; we're good. the build pulled the updated GCC package the second time around, and worked without issues.

for posterity, see here: http://us-east.manta.joyent.com/zettabot/public/openzfs/openzfs/pull/299/2/03-build.html

**Pull request merged**
