### PR TITLE
Merge illumos

### PR DESCRIPTION
**Pull request by ahrens**

### CODE REVIEW

**Comment by ahrens** [comment]
@zettabot go

**Comment by ahrens** [comment]
@zettabot go

**Comment by prakashsurya** [comment]
@zettabot go

**Comment by prakashsurya** [comment]
this failed the following test:
```
Tests with results other than PASS that are unexpected:
    FAIL online_offline/online_offline_002_neg (expected PASS)
```
with the following output:
```
$ cat online_offline/online_offline_002_neg/merged
ASSERTION: Turning both disks offline should fail.
SUCCESS: /usr/sbin/zpool online testpool.101343 c2t1d0
SUCCESS: /usr/sbin/zpool offline testpool.101343 c2t2d0
SUCCESS: /usr/sbin/zpool offline testpool.101343 c2t3d0
SUCCESS: /usr/sbin/zpool online testpool.101343 c2t2d0
cannot offline c2t1d0: no valid replicas
ERROR: /usr/sbin/zpool offline testpool.101343 c2t1d0 exited 1
NOTE: Performing local cleanup via log_onexit (cleanup)
SUCCESS: /usr/sbin/zpool online testpool.101343 c2t1d0
SUCCESS: /usr/sbin/zpool online testpool.101343 c2t2d0
SUCCESS: /usr/sbin/zpool online testpool.101343 c2t3d0
SUCCESS: /usr/bin/rm -rf /testdir101343/testfile1.101343
```
is this known failure, or is this new? I don't think I've seen this failure before.

**Comment by jwk404** [comment]
These tests have had failures in the past, but this one is new to me.

**Comment by ahrens** [comment]
I'm happy that the tests are running now.  It's possible that something in illumos has regressed this test, but that needn't stop us from syncing with illumos.

**Comment by ikozhukhov** [comment]
i think - need point advocates to move zfs related changes to openzfs PRs - and integrated zfs related changes to illumos from openzfs - not directly.
it is process integration issue.

**Pull request closed without merging**
