### PR TITLE
Fix gcc warnings

### PR DESCRIPTION
**Pull request by allanjude**
This reduces the number of warnings when compiling ZFS on FreeBSD on platforms like sparc64 that will use gcc 4.2 by improving the function prototypes.

### CODE REVIEW

**Comment by prakashsurya** [comment]
test this please

**Comment by ahrens** [comment]
The build failed; see http://build.prakashsurya.com:8080/job/openzfs-build-nightly/7/console

**Comment by prakashsurya** [comment]
@zettabot go

**Comment by prakashsurya** [comment]
@allanjude it looks like this is still failing the build: http://build.prakashsurya.com:8080/job/openzfs-build-nightly/15/console

I verified it's running your latest patch too.. you can see the specific version that it's building in this line:
```
Checking out Revision cbac7347033fdcbe110dd749628d4bf70281a1a3 (refs/remotes/origin/pr/5/merge)
```
and I manually fixed-up my `.git/config` to fetch pull requests by adding this:
```
fetch = +refs/pull/*:refs/remotes/openzfs/*
```
and then I can fetch, and query that specific commit to ensure it's building the latest version of the pull request:
```
commit cbac7347033fdcbe110dd749628d4bf70281a1a3 (openzfs/5/merge)
Merge: c295909 7cfa64b
Author: Allan Jude <github@shellfusion.ca>
Date:   Wed Oct 21 04:49:13 2015 +0000

    Merge 7cfa64b08650352e2dda540d7b12f47326d606ee into c29590968d8c4b9679d314de2e57779f523e3cc5

commit 7cfa64b08650352e2dda540d7b12f47326d606ee (openzfs/5/head)
Author: Allan Jude <allanjude@freebsd.org>
Date:   Wed Oct 21 00:48:30 2015 -0400

    Repair function prototype
```
(I wasn't sure if it was pulling the latest fix, so I wanted to double check; but it looks like it is)

**Comment by ahrens** [comment]
@allanjude Still interested in getting these changes in?

**Comment by allanjude** [comment]
I'll need to setup an IllumOS VM to debug these issues better, it works fine under clang on freebsd.
So yes, but the blocker is me not you.

**Comment by avg-I** [comment]
@allanjude if you need any help with that, just let me know - I have OI Hipster running on bhyve

**Comment by ahrens** [comment]
I'd be happy to have this type of change go in.  We haven't seen any work on this for half a year, so I'm going to close the PR.  Please open a new one if you have time to work on this again, @allanjude.

**Pull request closed without merging**
