### PR TITLE
7710 degradation after 7512 with GNU find and GNU echo

### PR DESCRIPTION
**Pull request by jwk404**

### CODE REVIEW

**Comment by jwk404** [comment]
@zettabot go

**Comment by jwk404** [comment]
I'd originally used `print` as Gary suggested in the bug, however that produces an error from dash on dilos. Changed to use find as Igor originally suggested.

**Comment by jwk404** [comment]
@zettabot go

**Comment by jwk404** [comment]
@zettabot go

**Comment by ikozhukhov** [comment]
LGTM, thanks

**Comment by pcd1193182** [comment]
LGTM

**Pull request closed without merging**
