### PR TITLE
6385 Fix unlocking order in zfs_zget()

### PR DESCRIPTION
**Pull request by ryao**
https://github.com/zfsonlinux/zfs/commit/f3ad9cd67ae57760a7ec9e8cdb0e33aa8bbea4d0

Signed-off-by: Richard Yao <ryao@gentoo.org>
Signed-off-by: Brian Behlendorf <behlendorf1@llnl.gov>

### CODE REVIEW

**Comment by ahrens** [comment]
jenkins, test this please

**Comment by ahrens** [comment]
Code looks good; will merge once we get the test results

**Comment by prakashsurya** [comment]
@ahrens I need to add you to the admin list before you can trigger the tests.

**Comment by prakashsurya** [comment]
@zettabot go

**Comment by prakashsurya** [comment]
retest this please

**Comment by prakashsurya** [comment]
@zettabot go

**Comment by prakashsurya** [comment]
@zettabot go

**Comment by avg-I** [comment]
This pull request would sound much less alarming to me if it said "fix **un**locking order".

**Comment by ryao** [comment]
@avg-I Good catch.

**Comment by ahrens** [comment]
@zettabot go

**Comment by dankimmel** [comment]
Looks good to me.

**Comment by ahrens** [comment]
@avl-l should I count you as a code reviewer?

**Comment by avg-I** [comment]
@ahrens  yes.

**Comment by lundman** [comment]
Running a version of this now, LGTM.

**Comment by ahrens** [comment]
@lundman thanks for the review -- sorry I just saw your email after I pushed and didn't include you in the list of reviewers :(

**Pull request closed without merging**
