### PR TITLE
7039 rework on environment definitions in zfs tests

### PR DESCRIPTION
**Pull request by ikozhukhov**
illumos bug: https://www.illumos.org/issues/7039
it contain example how we can override environment variables if needed.

this update important to me for run tests on DilOS and smartos based env where i need redefine environment variables.

### CODE REVIEW

**Comment by ahrens** [comment]
@zettabot go

**Comment by ahrens** [comment]
@jwk404 can you take a look?

**Comment by jwk404** [comment]
I still don't believe this is the right solution. With this solution, there's nothing programmatic that prevents new usages of "cat" as opposed to "$CAT" and then we're relying on whatever $PATH is set to. Would you mind holding off on this change until I can present an alternative?

**Comment by ikozhukhov** [comment]
i need these chnges - because on DilOS i need to use /system/bin with some components and on smartos basedo env i need to use :
SUDO=/opt/local/bin/sudo
and
PYTHON=/opt/local/bin/python

i have to use the same tests sources without modificationsa and i have tested my changes on DilOS and smartos based env.
i’m not sure symbolic links can fix it better instead of external scripts with : export CAT=/system/bin/cat - if needed.
we have to use components from cfg file instead of from PATH - because on some system we have /usr/gnu/bin in first place, on other systems we can /opt/local/bin in furst place

-Igor

**Comment by jwk404** [comment]
LGTM. This can unblock you, and we can improve on it later.

**Comment by ahrens** [comment]
I assume this is incompatible with https://github.com/openzfs/openzfs/pull/174, which is merged.

**Pull request closed without merging**
