### PR TITLE
8484 Implement aggregate sum and use for arc counters

### PR DESCRIPTION
**Pull request by prakashsurya**
Reviewed by: Pavel Zakharov <pavel.zakharov@delphix.com>
Reviewed by: Matthew Ahrens <mahrens@delphix.com>

In pursuit of improving performance on multi-core systems, this patch
implements fanned out counters and uses them to improve the performance of
some of the arc statistics. These stats are updated extremely frequently,
and can consume a significant amount of CPU time.

The cityhash code is copied from google's github, where it is MIT licensed.

Upstream bugs: DLPX-51685

### CODE REVIEW

**Comment by tonyhutter** [comment]
What kind of performance increases are you seeing?

**Comment by prakashsurya** [comment]
@ahrens @pcd1193182 can either of you comment on the performance of this? from what I remember, it was a little complicated, due to some other bottlenecks that we haven't yet pushed fixes for.

looking at our internal review, it says this patch increased performance from ~9300 MB/s to ~11200 MB/s; but that was tested with some other experimental patches to address bottlenecks elsewhere on the system. without these additional patches, the performance improvement was modest, going from ~5810 MB/s to 5870 MB/s. with that said, I think the bottlenecks seen elsewhere might be illumos specific, so it'd be interesting to get results from another platform.

**Comment by idodeclare** [comment]
Hi, Prakash,

The former implementation of dbuf.c's dbuf_hash() kept the lower six bits of the the 64-bit value of (void *os) out of the hash calculation. Likewise, the former implementation of arc.c's buf_hash() kept the lower eight bits of (uint64_t spa) out of the hash calculation. Is there no meaningful impact to your new implementation using those formerly-excluded bits in the cityhash?

Regards.

**Comment by pcd1193182** [comment]
Hi @idodeclare, including the lower 8 bits of the spa and many more bits of the os (because we're dropping the lower 8 and then & with 0xFF, so we only get bits 8-15) does not decrease the quality of the hashing. It will not cause any new collisions which did not already occur, and we perform a full equality check to find the appropriate element, so it will not result in incorrect return values.

**Comment by idodeclare** [comment]
Hi, @pcd1193182. I was inquiring about the inverse—whether including more information in hash will cause hashing to diverge where it was previously equal for similar values of \`os' or \`spa'.

**Comment by pcd1193182** [comment]
That can only be a good thing, no? Fewer hash collisions will generally result in higher performance. Even if you do lots of lookups to similar-argument dbufs at about the same time, we store them using chaining, so it doesn't get you any cache effect wins.

**Comment by idodeclare** [comment]
To be clearer, mine was not a question of quality of hashing—and certainly not of more collisions—but of identity, which you answered with "perform a full equality check to find the appropriate element." That was not clear from the diff. I.e. revision of the included bits without comment was what spurred my question.

**Comment by pcd1193182** [comment]
@idodeclare Ah, I understand now. Sorry for the confusion. You can see the equality check in dbuf.c immediately below the diff, in dbuf_find, and in arc.c in buf_hash_find.

**Comment by prakashsurya** [comment]
There were some concerns about this patch raised during the RTI, see here for more details: https://illumos.topicbox.com/groups/advocates/Te0a7c923a738145f-M0fcb9388d77093699c17c54d

I'm closing this, and will re-open when I get some time to do the testing requested in the RTI thread linked above.

**Comment by prakashsurya** [comment]
This is supersceded by #552

**Pull request closed without merging**
