### PR TITLE
Various changes to fix silent ONU failure via Jenkins testing

### PR DESCRIPTION
**Pull request by prakashsurya**

### CODE REVIEW

**Comment by prakashsurya** [comment]
@pyhalov do you know what might be causing this build failure? do I need to do anything differently since the shift to GCC 6?

**Comment by pyhalov** [comment]
https://www.illumos.org/issues/9205 - I think it's awful that we still depend on parts of studio to build the gate and nobody cares...

**Comment by pyhalov** [comment]
https://illumos.org/issues/6375

**Comment by prakashsurya** [comment]
Thanks @pyhalov. I stumbled on illumos 6375 earlier today, which led to me trying out installing the Sun Studio package to begin with. I think I'm good to go now. I appreciate all the help.

**Comment by jasonbking** [comment]
FYI, a webrev is available here: http://cr.illumos.org/~webrev/jbk/demangle/

**Pull request closed without merging**
