### PR TITLE
Reboot and verify kernel version after upgrade

### PR DESCRIPTION
**Pull request by prakashsurya**

### CODE REVIEW

**Comment by pyhalov** [comment]
Sorry, it seems I should fix build-essential for now...

**Comment by pyhalov** [comment]
I hope this will fix it - https://github.com/OpenIndiana/oi-userland/commit/281ad3484218af2edeb128a6246cfb60296f3066

**Comment by prakashsurya** [comment]
Thanks, I'll re-run the build.

**Comment by prakashsurya** [comment]
This is superseded by https://github.com/openzfs/openzfs/pull/575

**Pull request closed without merging**
