### PR TITLE
7535 need test for resumed send of top most filesystem

### PR DESCRIPTION
**Pull request by dankimmel**
Reviewed by: George Wilson <george.wilson@delphix.com> ( @grwilson )
Reviewed by: Matthew Ahrens <mahrens@delphix.com> ( @ahrens )

Expand test coverage to include resumed send from the root of a pool.

Upstream bugs: QA-5943, QA-6028

### CODE REVIEW

**Comment by prakashsurya** [comment]
@zettabot go

**Comment by dankimmel** [comment]
@zettabot go

**Comment by dankimmel** [comment]
@zettabot go

**Comment by dankimmel** [comment]
The tests are passing except for a couple of unrelated failures:

- `zfs_inherit_003_pos` is failing due to a test bug that we've fixed downstream.
- `zfs_acl_chmod_xattr_001_pos` is unrelated to my changes and not easily reproducible with or without my changes; I'm filing a (downstream) bug to investigate it more.

**Comment by dankimmel** [comment]
@zettabot go

**Comment by dankimmel** [comment]
The `zloop` failure looks like a known bug (`DLPX-45535 ztest failure in dbuf_read_impl` -- not visible).

**Comment by prakashsurya** [comment]
I just opened https://github.com/openzfs/openzfs/pull/237 with our internal fix for that zloop failure.

**Comment by dankimmel** [comment]
@zettabot go

**Pull request closed without merging**
