### PR TITLE
Add a manual for ztest.

### PR DESCRIPTION
**Pull request by sevan**
Based on the comments in ztest.c, via NetBSD.

### CODE REVIEW

**Comment by sevan** [comment]
I have not added the new file to Makefile for inclusion in a build, yet. Is adding the new file to the `MANFILE` section of `openzfs/usr/src/man/man1/Makefile` sufficient?

**Comment by ahrens** [comment]
You'll also need to add the manpage to the package manifest, `usr/src/pkg/manifests/system-file-system-zfs.mf`.  When looking at another change that added a manpage, I see a few other files that were also updated.  E.g. see dfc115332c94a2f62058ac7f2bce7631fbd20b3d and search for `zfs-program`

**Comment by sevan** [comment]
I've added this manual under the 1 category, is that correct or should it actually be in the 1m category on Illumos?

**Comment by ahrens** [comment]
zdb and zstreamdump manpages are in `1m`, so that's probably where this belongs as well.

**Comment by ikozhukhov** [comment]
i think, will be better move to .8 and on illumos too

**Comment by prakashsurya** [comment]
@sevan can you open an illumos bug for this?

**Comment by sevan** [comment]
@prakashsurya [done](https://www.illumos.org/issues/10512)

**Comment by prakashsurya** [comment]
Thanks. I'll work on getting the RTI open for this today.

**Comment by prakashsurya** [comment]
This is failing the build:
```
==== cstyle/hdrchk errors ====

dmake: Warning: Command failed for target `man'
dmake: Warning: Command failed for target `man1m'
dmake: Warning: Command failed for target `ztest.1m.check'
dmake: Warning: Target `check' not remade because of errors
mandoc: ztest.1m:31:11: WARNING: unknown manual section: Dt ... 1m
```

**Comment by sevan** [comment]
@prakashsurya That highlights that your instance of mandoc is unaware of the 1m category. So should the manual be recategorised into 1 as it was originally or should mandoc in illumos become 1m aware?

**Comment by prakashsurya** [comment]
@sevan Sorry for the delay. I'm guessing the issue is you're using "1m" in the manpage, when it should be "1M" (e.g. zdb's manpage uses "1M"). I'll make this change locally and try it out; i.e.
```
--- a/usr/src/man/man1m/ztest.1m
+++ b/usr/src/man/man1m/ztest.1m
@@ -28,7 +28,7 @@
 .\" POSSIBILITY OF SUCH DAMAGE.
 .\"/
 .Dd December 10, 2018
-.Dt ZTEST 1m
+.Dt ZTEST 1M
 .Os
 .Sh NAME
 .Nm ztest
```

**Comment by prakashsurya** [comment]
illumos RTI is [here](https://illumos.topicbox.com/groups/advocates/T880b828ce57c5989/rti-10512-add-manual-for-ztest1)

**Pull request closed without merging**
