### PR TITLE
5752 dump_nvlist() is not aware of boolean array

### PR DESCRIPTION
**Pull request by avg-I**
Issue: https://www.illumos.org/issues/5752
FreeBSD commit: https://svnweb.freebsd.org/base?view=revision&revision=282121

### CODE REVIEW

**Comment by avg-I** [comment]
Hmm, I actually wonder if this change is appropriate for OpenZFS repository given that nvlists are used beyond ZFS in illumos. Should this change rather go through the normal illumos channels?

**Comment by ahrens** [comment]
@avg-I I'm fine with taking the change here and then upstreaming to illumos for you.  Let's just be sure we get reviewers from the broader illumos community.  I'll be posting to the mailing list soon to solicit reviews on these pull requests; that should start getting some eyeballs.

**Comment by dankimmel** [comment]
This looks good to me. Ship it!

**Comment by wca** [comment]
LGTM

**Comment by ahrens** [comment]
LGTM

**Comment by ahrens** [comment]
@zettabot go

**Comment by ahrens** [comment]
@avg-I I just wanted to confirm that your email address in the commit is the one you want to use:
Author:    Andriy Gapon <avg@icyb.net.ua>

**Comment by avg-I** [comment]
@ahrens I would like it to be <andriy.gapon@clusterhq.com>
I am juggling commits between multiple repositories with different configuration, sometimes that leads to confusions.

**Pull request closed without merging**
