### PR TITLE
WIP: ZIL Pipelining

### PR DESCRIPTION
**Pull request by ryao**
This is still a WIP. It doesn't yet pass every regression test in the ZoL
buildbot. Testing has been done solely against the current ZoL stable branch.
It is being pushed for performance evaluation of the approach.

Signed-off-by: Richard Yao <richard.yao@prophetstor.com>

### CODE REVIEW

**Comment by prakashsurya** [comment]
I was able to get a successful build after applying this diff: https://gist.github.com/prakashsurya/c90666059a38f75013a5369bae902cfd

But now when running zloop I quickly run into this failure:
```
06/13 21:55:46 ztest -VVVVV -m 2 -r 0 -R 1 -v 2 -a 12 -T 18 -P 13 -s 128m -f /var/tmp/git-zfs-zloop-vDXxxZP
*** ztest crash found - moving logs to /var/tmp/git-zfs-zloop-vDXxxZP/zloop-170613-215551
mdb: failed to add zil_writer_cache walker: walk name already in use
mdb: failed to add zil_writer_cache walker: walk name already in use
*** core @ /var/tmp/git-zfs-zloop-vDXxxZP/zloop-170613-215551/core:
debugging core file of ztest (64-bit) from ps-zloop.dcenter
file:
/net/scottie/data/jenkins/zfs-make/psurya/openzfs-404-delphix/proto/root_i386/us
r/bin/amd64/ztest
initial argv:
/net/scottie/data/jenkins/zfs-make/psurya/openzfs-404-delphix/proto/root_i386/u
threading model: native threads
status: process terminated by SIGSEGV (Segmentation Fault), addr=360
libzpool.so.1`zio_shrink+0x1b(0, 1000)
libzpool.so.1`zil_lwb_write_start+0x2ba(2bc1f10, 2bc3ef0)
libzpool.so.1`zil_commit_writer+0x1bb(1f97680)
libzpool.so.1`zil_commit+0x2d(1f97680, 0)
ztest_freeze+0xb5()
ztest_init+0x1fb(fffffd7fff290498)
ztest_run_init+0x79()
main+0x7f0(1, fffffd7fffdffa18)
_start+0x6c()
```
I'll try to make some time to look some more into this later.

**Comment by ryao** [comment]
@prakashsurya Thanks for that. I think I see why it failed there. That `lwb = zil_lwb_write_start(zilw, lwb);` line after `/* write the last block out */` was not supposed to be there. I manually merged a rather large *.rej file with the intention of leaning on the buildbot to help me catch mistakes. That line was one of them. I just fixed the issues that the buildbot found. Hopefully zloop will work better now.

**Comment by prakashsurya** [comment]
I just tried to deploy this chance and hit this panic on boot:
```
panic[cpu0]/thread=ffffff03155a64a0: assertion failed: cio->io_child_type <= pio->io_child_type, file: ../../common/fs/zfs/zio.c, line: 400

ffffff000ddd8a50 fffffffffba96ba4 ()
ffffff000ddd8aa0 zfs:zio_add_child+120 ()
ffffff000ddd8b40 zfs:zio_create+303 ()
ffffff000ddd8be0 zfs:zio_rewrite+84 ()
ffffff000ddd8c70 zfs:zil_lwb_write_init+132 ()
ffffff000ddd8d00 zfs:zil_lwb_commit+91 ()
ffffff000ddd8d90 zfs:zil_commit_writer+107 ()
ffffff000ddd8dc0 zfs:zil_commit+2d ()
ffffff000ddd8e30 zfs:zfs_fsync+bc ()
ffffff000ddd8e90 genunix:fop_fsync+44 ()
ffffff000ddd8ec0 genunix:fdsync+3c ()
ffffff000ddd8f10 unix:brand_sys_syscall32+17a ()
```
I haven't tried to root cause it yet, but I can try to do that if needed later this week.

**Comment by ryao** [comment]
@prakashsurya We are only using zvols at work, where it works fine thus far. Encountering an issue with a filesystem would explain why the buildbot is catching issues while our own testing at work is not. I have a deadline to meet on the 18th, but I'll see what I can do to run this down before then.

**Comment by prakashsurya** [comment]
OK, that makes sense. No worries if you don't have time to look into this, I can try and make some time later to do that.

**Pull request closed without merging**
