### PR TITLE
XXXX Automated Testing using Jenkins and EC2

### PR DESCRIPTION
**Pull request by prakashsurya**
This adds the necessary files such that we can leverage Jenkins and
Amazon EC2 to perfrom basic sanity testing of OpenZFS pull requests.
With the included "Jenkinsfile", the following will be performed for
each pull request submitted:

  1. Create a new VM in Amazon EC2 based on OpenIndiana "Hipster"
  2. Configure the VM from (1) to support building OpenZFS
  3. Perform a full "nightly" build
  4. Run "git nits"
  5. Upgrade the VM from (1) using the build products from (3)
  6. Clone the upgraded VM from (5), and run the following tests (each
     test being run in parallel, and on an independent Amazon EC2 VM):
     "libctest", "ostest", "utiltest", "zfstest", and "zloop".

Additionally, the contents of "/var/tmp/test_result" and the log file
associated with each individual test will be archived and available for
download via the Jenkins UI; which is useful for debugging failed tests.

### CODE REVIEW

**Comment by danmcd** [comment]
Please make sure the illumos bits of this that can be upstreamed are.  Thank you. :)

**Comment by prakashsurya** [comment]
@danmcd we've done that with a couple already: https://github.com/illumos/illumos-gate/commit/2a81eaec72 and https://github.com/illumos/illumos-gate/commit/dde8fce613

I'd love to get https://github.com/openzfs/openzfs/pull/336/commits/f7cc00eca5 landed to illumos; if I can get some support of that on the ML thread and/or PR, I'll get the RTI open. I've been hesitant since it might introduce a change in behavior for some workloads (expose the XDF when it wouldn't have otherwise been exposed, while _also_ exposing the ATA device). The PR for that is also open here: https://github.com/openzfs/openzfs/pull/281

The PR for https://github.com/openzfs/openzfs/pull/336/commits/44c2f9d0e8 is here: https://github.com/openzfs/openzfs/pull/324 .. I try and finish that one up. With that said, I could drop that commit from this PR since it's not _required_ to transition the testing to EC2.

And the last one is: https://github.com/openzfs/openzfs/pull/336/commits/be934dad94 .. My assumption has been that this is not acceptable for illumos, so I haven't tried to get that integrated. Do you agree?

**Comment by danmcd** [comment]
Correct on apix_enable change, not good for upstream (though I wonder if there's a way early in boot to detect Xen and tweak apix_enable?).  The other two are pretty much like you said, however.  Thank you.

**Comment by yuripv** [comment]
> though I wonder if there's a way early in boot to detect Xen and tweak apix_enable?

Hopefully, determine_platform() has already been run, so it should be a check of platfrom_type against HW_XEN_HVM.

**Comment by yuripv** [comment]
How about the following http://cr.illumos.org/~webrev/yurip/il-hvm-apix/? mail sent to developer@ as well.

**Comment by ikozhukhov** [comment]
will be better move it after:
 258  267          if (apix_enable == 0)
 259  268                  return (PSM_FAILURE);

also - maybe print warning about it to console/log - because we forgot to fix it :)

**Comment by prakashsurya** [comment]
thanks @yuripv, give me a couple days and i'll test that out.

**Comment by yuripv** [comment]
@prakashsurya I've submitted this change for RTI, so you'll have one thing less to worry about.

**Pull request closed without merging**
