### PR TITLE
Sequential Scan patches

### PR DESCRIPTION
**Pull request by kithrup**
My attempt to port the FreeBSD sequential scan changes (themselves ported from ZoL) to OpenZFS.

This is completely untested -- not even a build test.  As I mentioned on the mailing list yesterday, I'm not currently set up for that.  Even assuming it builds, it of course needs to be tested.  I was asked to create a PR, so I have done so.  I will not be upset if someone just takes these patches and completely redoes them; our goal is simply to try to have them upstreamed.

### CODE REVIEW

**Comment by alek-p** [comment]
Thanks for taking this on. Looks like https://github.com/zfsonlinux/zfs/commit/a8b2e30685c9214c followup patch hasn't been ported yet, perhaps you're willing to do it?

**Comment by ikozhukhov** [comment]
have to update changes with changed API in range_tree_create(range_tree_ops_t *ops, void *arg)
instead of to use additional (3) parameter for mutex.

**Comment by ikozhukhov** [comment]
well, right now, illumos sources are using range_tree_create(range_tree_ops_t *ops, void *arg) - with 2 parameters, not 3.
it was changed with device removal.
i think, have to recheck your implementation with new function range_tree_create(range_tree_ops_t *ops, void *arg)

**Comment by ikozhukhov** [comment]
https://github.com/openzfs/openzfs/commit/f539f1eb707e3af0ec4617c664b67dff46a0c173
it is change.
at line:
https://github.com/openzfs/openzfs/commit/f539f1eb707e3af0ec4617c664b67dff46a0c173#diff-a52d460452258191b59886bbcfaa23b3R129

**Comment by ikozhukhov** [comment]
merge conflict in dsl_scan.c:

```<<<<<<< HEAD
		/* Embedded BP's have phys_birth==0, so we reject them above. */
		ASSERT(!BP_IS_EMBEDDED(bp));
=======
		f (BP_IS_EMBEDDED(bp)) {
				count_block(scn, dp->dp_blkstats, bp);
				return (0);
		}
>>>>>>> My attempt to port the FreeBSD sequential scan changes (themselves
```

**Comment by kithrup** [comment]
You're going to have to supply a bit more information than that, I'm afraid.  Is that around line 3512?

I _think_ it should go with "my" version.

**Comment by ikozhukhov** [comment]
huh - did you try rebase to master and just push your changes with -f (force)?
right now your changes are overloaded

**Comment by kithrup** [comment]
> huh - did you try rebase to master and just push your changes with -f (force)?
> right now your changes are overloaded

sigh.  I don’t know how to git very well, obviously.  I did not do a push -f,
however.

**Comment by ikozhukhov** [comment]
well, right now will be better:
- get openzfs tree with latest updates from master
- create your branch and put changes on it
- commit all in one over latest openzfs tree

**Pull request closed without merging**
