### PR TITLE
6327 devfsadm and bootadm taking long time for configs with large num…

### PR DESCRIPTION
**Pull request by ahrens**
…ber of zvols

Reviewed by: Matthew Ahrens mahrens@delphix.com
Reviewed by: Sebastien Roy sebastien.roy@delphix.com
Reviewed by: Eric Schrock eric.schrock@delphix.com

There are several problems here:
1. when running 'bootadm update-archive' I see that lots of time is
spent in newfs. The problem here is that this call is using libdiskmgt
to verify that the lofi device is not being used by anybody. Since the
lofi device was just created the use of libdiskmgmt here is unnecessary.
2. devzvol_readdir() traverses every snapshot.

I looked at removing the snapshots from /dev/zvol by making a change in
the zvol code. This does improve things but doesn't it solve it
completely. In my investigation I still saw that mkfs would still try to
lstat() every zvol snapshot even though the device node did not exist.

Digging further I think the real solution is to change the dev subsystem
to prevent both pseudo and the /dev/zvol links from being created.

This change adds a tunable which disables creation of /dev/zvol links
for snapshots. By default, the behavior is not changed, but if you don't
need to access zvol snapshots through /dev/zvol, you can disable them
for a nice performance improvement.

Upstream bugs: 23034

### CODE REVIEW

**Comment by ikozhukhov** [comment]
LGTM

**Comment by richardelling** [comment]
LGTM

**Comment by ahrens** [comment]
@ikozhukhov @richardelling I noticed that contrary to the description, the default is set to disable /dev/zvol snapshot links.  I was planning to fix that (make the default to enable the links, preserving the existing behavior), but thought I'd give you a chance to object in case your "LGTM" applies to the default being off.

**Comment by danmcd** [comment]
This seems like two bugs, one for create_ramdisk and the other for the devfs entries.

**Comment by ikozhukhov** [comment]
@danmcd - what is the bug with create_ramdisk?
as i can see - it has only new env var NOINUSE_CHECK=1
@ahrens - thanks for point to /dev/zvol, will wait update

**Comment by ikozhukhov** [comment]
@ahrens - about NOINUSE_CHECK=1
i looked to another examples based on sources in tree - like usr/src/cmd/initpkg/swapadd.sh - we need to do:
NOINUSE_CHECK=1; export NOINUSE_CHECK
we need export this variable if we will fork process and try to use env vars outside script.

**Comment by danmcd** [comment]
@ikozhukhov - I mean I see two distinct fixes that shouldn't necessarily be tied together.  create_ramdisk using NOINUSE_CHECK is one bug & fix, and the changes in zvol is another bug & fix.

**Comment by richardelling** [comment]
@ahrens my preference is for volume snapshots to be hidden. Certainly in the use cases I care about, "access" to volume snapshots is via clones, not the snapshots themselves. This simplifies interfaces because few volume consumers truly understand the concept of readonly.

That said, it is perfectly ok to keep the current behaviour by default.

**Comment by GregorKopka** [comment]
ZoL has an inplementation of an inheritable dataset level property _snapdev_ that controls creation of device nodes for zvol snapshots:
https://github.com/zfsonlinux/zfs/search?q=snapdev&type=Code

Maybe you want to use this instead of a system-level tuneable since it offers better granularity of control?

**Comment by ahrens** [comment]
@danmcd OK, I'll hold off on this change and break it into two when I get a chance.

@ikozhukhov This way of setting env vars is fine -- in swapadd.sh it wants to set the env for all future commands in the script.  Here we are just setting it while running newfs.

@GregorKopka That sounds great, I'll withdraw this PR if someone (you?) opens a PR porting those changes.  Or if that doesn't happen, I'll put this in for now and we can remove it when _snapdev_ is ported at a later date.

**Comment by ahrens** [comment]
@danmcd I separated out the changes to create_ramdisk.sh per your request.

**Comment by danmcd** [comment]
Thanks @ahrens - Ship this too.

**Pull request closed without merging**
