### PR TITLE
6931 lib/libzfs: cleanup gcc warnings

### PR DESCRIPTION
**Pull request by ikozhukhov**

### CODE REVIEW

**Comment by ahrens** [comment]
@zettabot go

**Comment by yuripv** [comment]
The assert(!"text") looks pretty weird, I see that there already was one such statement, but assert(3C) says:

    Since assert() is implemented as a macro, the expression may not
    contain any string literals.

**Comment by ahrens** [comment]
@zettabot go

**Comment by ahrens** [comment]
@zettabot go

**Comment by ahrens** [comment]
changes look good to me.

**Comment by yuripv** [comment]
That doesn't answer my concerns about assert(3C) abuse.

**Comment by ahrens** [comment]
Looks like lots of setups failed in zfs-test.  The previous 2 test runs of this PR failed in similar ways, and I haven't seen this failure before (I checked the 3 previous runs and they didn't have this failure mode).  @prakashsurya can you check the log file and post it here or help @yuripv to debug?

**Comment by yuripv** [comment]
Again, this is abusing the libzfs in the wrong way, If you are accepting this, please fix assert(3C).

**Comment by ahrens** [comment]
@yuripv point taken.  Do you know why the assert manpage says that?  What goes wrong if you use a string literal?

**Comment by ikozhukhov** [comment]
@yuripv take a look at https://github.com/openzfs/openzfs/commit/c16bcc4577f389573eff411c7b7e040294078c3b#diff-28076b838bad2656d2658ec433cd46f2R4477
it was proposed by Matt and working as well.

**Comment by ahrens** [comment]
@zettabot go

**Comment by ahrens** [comment]
@zettabot go

**Comment by ahrens** [comment]
@yuripv do you have any idea *why* the manpage says that?  We've been using ASSERT() in the kernel this way since the beginning of ZFS, and in userland since at least May 2010 (zpool_scan() does `assert(!"unexpected result");`).  Do you have a recommendation for how to accomplish the goal here, in lieu of `assert(!"descriptive string")`?  Or do you think we should change the manpage?

**Comment by ahrens** [comment]
@ikozhukhov Please fix the following cstyle issues:

usr/src/common/zfs/zfs_deleg.c: 181: line > 80 characters
usr/src/lib/libzfs/common/libzfs_pool.c: 644: line > 80 characters
usr/src/lib/libzfs/common/libzfs_pool.c: 644: continuation should be indented 4 spaces

**Comment by ikozhukhov** [comment]
@ahrens - fixed

**Comment by ahrens** [comment]
@zettabot go

**Pull request closed without merging**
