### PR TITLE
basic set of casesensitivity/normalization test cases for zfs-tests

### PR DESCRIPTION
**Pull request by yuripankov**
Create a basic set of casesensitivity/normalization test cases for zfs-tests. Currently lookup and delete are checked.

This covers known delete issue - https://www.illumos.org/issues/1300.

### CODE REVIEW

**Comment by ahrens** [comment]
@zettabot go

**Comment by yuripankov** [comment]
I've fixed the build issue, how do I tell zettabot to try it again?

**Comment by ahrens** [comment]
@zettabot go

**Comment by yuripankov** [comment]
Updated once again, hopefully I got everything right this time - tested to build and run.

**Comment by ahrens** [comment]
@zettabot go

**Comment by yuripankov** [comment]
Again, please...

**Comment by ahrens** [comment]
@zettabot go

**Comment by yuripankov** [comment]
Fixed setup...

**Comment by yuripankov** [comment]
Could we please run the tests again? Sorry for so many failures...

**Comment by ahrens** [comment]
@zettabot go

**Comment by yuripankov** [comment]
Looks like finally it builds and runs. The following are expected failures:

Tests with results other than PASS that are unexpected:
    FAIL casenorm/insensitive_formd_delete (expected PASS)
    FAIL casenorm/mixed_formd_lookup (expected PASS)
    FAIL casenorm/sensitive_formd_delete (expected PASS)
    FAIL casenorm/insensitive_none_delete (expected PASS)
    FAIL casenorm/mixed_formd_delete (expected PASS)

The issues are tracked as https://www.illumos.org/issues/1300.

**Comment by yuripankov** [comment]
Anything else I need to do here?

**Comment by ahrens** [comment]
@jwk404 can you take a look at this?  Are we OK with adding failing tests (which expose real bugs)?  Seems like a good form of test-driven development to me, we will just have to mark them as known failures.

**Comment by jwk404** [comment]
LGTM

I'm fine with adding tests that fail if, as in this case, they fail against a known bug that's already filed.

**Comment by ahrens** [comment]
I've added an exception for the failing tests.

**Comment by ahrens** [comment]
@zettabot go

**Comment by ahrens** [comment]
@zettabot go

**Comment by ahrens** [comment]
Note: ztest failure is unrelated to these changes. http://build.prakashsurya.com:8080/job/openzfs-regression-tests/176/

**Pull request closed without merging**
