### PR TITLE
Merge illumos

### PR DESCRIPTION
**Pull request by ahrens**

### CODE REVIEW

**Comment by ahrens** [comment]
test failure is a pre-existing bug: ztest fails with:
`assertion failed for thread 0xf09b6240, thread-id 601: refcount_count(&tx->tx_space_written) + delta <= tx->tx_space_towrite (0x136650000 <= 0x136620000), file ../../../uts/common/fs/zfs/dmu_tx.c, line 1371`

**Comment by prakashsurya** [comment]
@ahrens do you think we should open bugs in the openzfs-build repo to track these failures?

**Comment by stevenburgess** [comment]
This PR brings up an interesting point: how do we want keep the OpenZFS repo up to date with illumos changes? The [initial commit](https://github.com/openzfs/openzfs/commit/c29590968d8c4b9679d314de2e57779f523e3cc5) did not include any history, but the entire illumos history was eventually [merged in] (https://github.com/openzfs/openzfs/commit/5e0929bd169e776fb375a8c75f5736f1cae6d9df).

I think the way that we are rebasing PRs on top of the current OpenZFS head is great, and it lends itself to us just continuously rebasing the OpenZFS tree on top of the illumos tree. This way, we can think of git diff OpenZFS...illumos as the set of things that still need to get put back into illumos.

For an example of why the current merge in strategy will get confusing, the results of [this PR](https://github.com/openzfs/openzfs/pull/13) has two different commits associated with it

[OpneZFS](https://github.com/openzfs/openzfs/commit/b621ee9a67a0184ee2eb2d7461a1e7966f0e45d2)
[illumos](https://github.com/illumos/illumos-gate/commit/c71c00bbe8a9cdc7e3f4048b751f48e80441d506)

In a rebase strategy, the first SHA would be left off the rebase when the change was finally upstreamed. Less than ideal that the SHA in the PR will not show up in the log, but we can either post the new SHA in the PR, or just ignore it because it will still have the same illumos ticket ID, which is easy to search for.

Looks like the current strategy has lead to a rebase conflict, but if anyone would like to see my idea attempted, I would be willing to work through it and push my changes to a personal fork.

**Comment by prakashsurya** [comment]
The current strategy we've decided on, to keep us in sync with illumos,         
is to merge in changes from illumos into the OpenZFS repo on a recurring        
basis (daily, weekly, monthly, w/e). Thus, the current work flow looks a        
bit like this:                                                                  
                                                                                
    1. We land pull requests onto OpenZFS, slightly diverging from              
       illumos                                                                  
    2. illumos lands patches submitted to them by non-OpenZFS folks             
       (usually patches unrelated to the illumos ZFS source), slightly          
       diverging from OpenZFS                                                   
    3. We push patches unique to OpenZFS (i.e. the patches we land via          
       our pull requests) back to illumos via the normal illumos RTI            
       process; reducing the divergence between the illumos ZFS and             
       OpenZFS implementations.                                                 
    4. We merge in the entire illumos tree periodically, to pull in             
       changes that were landed in illumos (again, usually non-ZFS              
       changes) to reduce the divergence even more.                             
                                                                                
As a result of this type of work flow, the following subtleties arise:          
                                                                                
    - OpenZFS will rarely be completely "in sync" with illumos. Even            
      after a merge with illumos, it'll likely be the case that we have         
      outstanding patches in OpenZFS that still remain to land in               
      illumos. So, best case we only have "extra" changes that need to          
      be pushed to illumos, and worst case we have extra changes to push        
      and illumos has also has changes that we need to pull.                    
                                                                                
    - Since we're pushing changes to illumos via the normal RTI process,        
      and then merging their tree in with OpenZFS, there will inevitably        
      be "two commits" for each change that we land in OpenZFS. One that        
      landed in our tree first, and then the second that landed in              
      illumos and we inherit via the merge with illumos. To me, this is         
      a non-issue since the two patches will likely be identical (or at         
      least very close to it). Is there a specific reason why you think         
      this is an issue? Maybe I'm overlooking something?                        
                                                                                
One reason why I'm against the idea of rebasing the OpenZFS repository          
on top of illumos instead of our current merge workflow, is that it'll          
rewrite the history and prevent a simple "pull" from working. Each time         
a downstream consumer of OpenZFS wants to pull our changes, they'll have        
to do a "force" pull since we will have rewritten the history of the            
branch.                                                                         
                                                                                
I've seen this "rebase" workflow work relatively well for small projects        
in which the "master" branch isn't actually rebased. Instead, an new            
branch is created that is a rebased version of the previous branch.             
Thus, no re-writing of the history, but at the same time the original           
branch is "abandoned" so it's effectively the same thing.                       
                                                                                
Merge conflicts are much more painful for rebasing many commits onto a          
new tree, too. But, practically, I don't think this will be a real issue        
for us since we plan to continually RTI our "local" commits to illumos,         
so we shouldn't have conflicts if we were to rebase instead of merge.           
                                                                                
So, to me, I'm in favor of merges because it doesn't rewrite the history        
which makes it more difficult for downstream consumers of the                   
repository. But, I don't think I fully understand your concerns about           
the "two commits" issue, so it's hard for me to weight that against the         
merge work flow. Can you elaborate a bit more about why this concerns           
you?                                                                            
                                                                                
Additionally, if we end up getting a lot of pull requests and                   
contributions from the community, I think the cost of doing an RTI will         
become unreasonable. In that case, I think it'll make sense to try and          
work with the illumos advocates to try and expedite the process of              
syncing our OpenZFS changes with illumos. One method I envision for that        
would be to, instead of RTI'ing each commit into illumos, simply merge          
OpenZFS into illumos. In that world, we wouldn't run into this "two             
commits for each pull request" scenario, as we would merge our local            
commits into illumos via a single merge commit to that repository; much         
like we do with changes made on illumos. At the surface it doesn't seem         
like us merging with illumos vs. rebasing onto illumos affects this long        
term idea, but it might be worth considering.                                   
                                                                                
Ultimately, to me, the most important things to maintain regardless of          
which work flow we choose, is this:                                             
                                                                                
    1. It needs to be easy for developers to push changes to OpenZFS.           
       This is definitely the most important thing, and the main reason         
       we created this repository to begin with. Getting all platforms          
       sharing code and reviewing other developers code, is good for            
       everybody using OpenZFS on any platform. Pull request seem like          
       the best method to facilitate this.                                      
                                                                                
    2. It needs to be easy for OpenZFS maintainers to accept changes            
       pushed to OpenZFS and quickly and painlessly get these integrated        
       into illumos. Which is why we require most of the same                   
       integration "rules" as illumos, and also why we continually keep         
       OpenZFS "in sync" with illumos as much as possible.                      
                                                                                
    3. It needs to be easy and intuitive for downstream folks to pull           
       the lastest version of OpenZFS, and merge our repository into            
       whatever work they may be doing. Which is why we've adopted a            
       strategy to merge with illumos instead of rebase.                        
                                                                                
I think using rebase instead of merge would probably help with point 2          
(much easier to get a definitive list of what remains to be pushed              
upstream, as you said), but I worry that it'll hurt point 3 (due to             
requiring "force" updates). I'm open to new ideas, though, and really            
appreciate the involvement; I just want to make sure we don't hurt an           
important use case while trying to cater to another.

**Comment by ahrens** [comment]
I agree with what @prakashsurya wrote, especially that if we were to rebase OpenZFS, it would be difficult for anyone to use OpenZFS as the upstream for their repo.

I would add that I don't want to make it a hard requirement for the OpenZFS repo to be tightly in sync with illumos.  The OpenZFS repo needs to serve the needs of the broader OpenZFS community, beyond just illumos.  While I intend to keep OpenZFS tightly in sync with illumos, I don't want to make technical decisions that would preclude OpenZFS-only commits if necessary.

**Comment by stevenburgess** [comment]
Thanks for the detailed response!

Each way has its own pros and cons, so as long as both ways are considered and we choose the ones whose strengths matches what we need, that’s a win. Both ways are viable, and neither one will lead to calamity. (and now that I have a more full understanding of our intentions, my suggestion does seem less ideal)

In that spirit, some additional problems a rebase strategy would introduce:
-How often do we rebase on illumos? Every commit?
-The SHA for a changeset can potentially change many many times.
-The workload is greater on the admins.

But the overarching benefit I see in a rebase strategy is a clear understanding of what changesets are where.

You mention that the diffs may be slightly different by the time they land in illumos. Lets say that for a certain patch, the OpenZFS group approves it as it is tn the GH PR. Then when it goes to illumos for RTI, they would prefer an ASSERT be added. Weeks later after the next illumos merge, if I were running OpenZFS/master, would I expect the ASSERT to be there or not? If I knew the bug ID and searched for it in the logs, I would find the two versions, but which one would I expect to be running, and how do I determine which one it is?

I was not considering the impact a rebase strategy would have on ‘git pull’, because I do not use git pull (I fetch frequently, then use git checkout (-b/-B) to get the repo in a state I want). You are correct, this would make the git pull workflow significantly more risky.

I think the advantage for the downstream repos is going to be the PR process and the discussions. I don’t expect downstream maintainers to source this repo as a submodule or as a sub-tree, because it would pull in all of illumos. In that case, neither method really affects them, because they will just be reaching in and taking out the files they want (HEAD SHA will not really matter to them). Once we reach the goal of independant files not tethered to any implementation, this whole discussion becomes moot, because illumos will no longer be merged in.

Seems like we have a pretty good coverage of the pros and cons, so unless any of the above sound particularly compelling, continue to :shipit:

**Comment by prakashsurya** [comment]
> You mention that the diffs may be slightly different by the time they land in illumos. Lets say that for a certain patch, the OpenZFS group approves it as it is tn the GH PR. Then when it goes to illumos for RTI, they would prefer an ASSERT be added. Weeks later after the next illumos merge, if I were running OpenZFS/master, would I expect the ASSERT to be there or not? If I knew the bug ID and searched for it in the logs, I would find the two versions, but which one would I expect to be running, and how do I determine which one it is?

In this case, the illumos version should be authoritative. Any changes (additions or removals) should be reflected in the OpenZFS tree after the upstream'ed commit is merged back into OpenZFS. This information should be able to be retrieved manually, by inspecting the tree of commits (e.g. `git log --oneline --graph`), looking for the commit in both "branches" and then inspecting the merge commit to ensure it was merged properly. For example, take this pull request: https://github.com/openzfs/openzfs/pull/16

I can look at the history and see exactly where it was landed in both OpenZFS and illumos:
```
$ git log --oneline --graph openzfs/master | cut -c 1-80 | head -n 40
* adec812 6414 vdev_config_sync could be simpler Reviewed by: George Wilson <geo
* fabbbb0 6391 Override default SPA config location via environment Reviewed by:
* 1fca770 6421 Add missing multilist_destroy calls to arc_fini Reviewed by: Dan 
* b621ee9 6388 Failure of userland copy should return EFAULT Reviewed by: Brian 
* 48d66fc 6368 Remove superfluous statement Reviewed-by: Ned Bass <bass6@llnl.go
* 7da97da 6401 run.py should reopen files if they encounter transient I/O errors
* fc00a90 5752 dump_nvlist() is not aware of boolean array Reviewed by: Dan Kimm
* a9272e3 6389 Use (void) memcpy(), not (void *) memcpy() Reviewed by: Brian Beh
* f2ec8f3 6386 Fix function call with uninitialized value in vdev_inuse Reviewed
*   186ab8d Merge pull request #28 from ahrens/merge
|\  
| *   00c4ece Merge remote-tracking branch 'illumos/master' into openzfs-merge
| |\  
|/ /  
| * f34d737 5963 rmis should be removed from arcstat manpage Reviewed by: Matthe
| * 1df447e 6390 Free props in ztest_init() Reviewed by: Brian Behlendorf <behle
| * eaef6a9 6385 Fix unlocking order in zfs_zget Reviewed by: Brian Behlendorf <
| * 07b64d1 6376 segmentation fault when sharing with 'sec=none,root=*' options 
| * 4eab410 6369 remove SVM tests from ZFS test suite Reviewed by: John Kennedy 
| * cd8037e 6344 mdb choked on core file from newer platform Reviewed by: Robert
| * 4224188 6338 cannot use umem tools on mdb itself Reviewed by: Dave Pacheco <
| * b3700b0 6352 Updated DC locator for SMB and idmap Portions contributed by: M
| * ed81dd5 6351 Update smbsrv dtrace scripts and install them Reviewed by: Gord
| * 12b6558 1122 smbsrv should use SPNEGO (inbound authentication) Portions cont
| * 056d3a7 6343 zoneadmd parent needs to close open fds Reviewed by: Robert Mus
| * 78b013d 6394 ::mac_flow -s segfaults Reviewed by: Jason King <jason.brian.ki
| * 29e5475 6347 microfind is somewhat less than ideal Reviewed by: Patrick Moon
| * 075fab9 6353 POLLHUP not generated for disconnected Unix domain sockets Revi
| * 30a92f3 6373 README.mapfiles refers to wrong symbol version Reviewed by: Rya
* | b5e85c0 6390 Free props in ztest_init() Reviewed by: Brian Behlendorf <behle
* | d578e0e 6385 Fix unlocking order in zfs_zget() Reviewed by: Brian Behlendorf
* | 2bc93fe 6369 remove SVM tests from ZFS test suite Reviewed by: John Kennedy 
* |   5e0929b Merge illumos
|\ \  
| |/  
| * a443cc8 6292 exporting a pool while an async destroy is running can leave en
| * 1a49874 6372 remove ON_CRYPTO_BINS references from the env file and Install 
| * 38e64a3 6339 env file could figure out CODEMGR_WS automatically Reviewed by:
| * 4cb69ec 6335 need to use sed and awk from Makefile.master in head/Makefile R
| * b39b744 6319 assertion failed in zio_ddt_write: bp->blk_birth == txg Reviewe
```
It was first landed in OpenZFS here:
```
* | 2bc93fe 6369 remove SVM tests from ZFS test suite Reviewed by: John Kennedy 
```
And then later in illumos here:
```
| * 4eab410 6369 remove SVM tests from ZFS test suite Reviewed by: John Kennedy 
```
OpenZFS then picked up the version in illumos via the merge commit, here:
```
*   186ab8d Merge pull request #28 from ahrens/merge
|\  
| *   00c4ece Merge remote-tracking branch 'illumos/master' into openzfs-merge
```
there's two merge commits because Matt likely merged illumos to a local branch in his local repository, then opened a pull request with that merge commit, and then merged the merge commit into OpenZFS.

The data is all there, if we need to write some tools to get at this information a bit easier, then we can try to make some time to do that.

Ultimately, the question of "who's version is authoritative" is up to the maintainers of OpenZFS. If changes are made during the RTI process and those changes are also deemed appropriate for OpenZFS, then it's likely that the changes will get pulled in via the merge with illumos. With that said, it's possible that the illumos RTI process requires changes to the patch that are not appropriate to land in OpenZFS, in which case the merge commit will not pull in these additional changes and will use the version of the patch that had already landed in OpenZFS (via the original pull request).

Matt's comment:

> I would add that I don't want to make it a hard requirement for the OpenZFS repo to be tightly in sync with illumos. The OpenZFS repo needs to serve the needs of the broader OpenZFS community, beyond just illumos. While I intend to keep OpenZFS tightly in sync with illumos, I don't want to make technical decisions that would preclude OpenZFS-only commits if necessary.

Tells me that, while we want to stay as much in sync with illumos as possible, that's not a strict requirement. It's possible that we'll maintain differences that will never be brought into illumos, and that's OK (maybe differences introduced by the RTI process, but likely not). Just like there may be changes made in downstream versions of OpenZFS that will never be brought into OpenZFS.

> I think the advantage for the downstream repos is going to be the PR process and the discussions. I don’t expect downstream maintainers to source this repo as a submodule or as a sub-tree, because it would pull in all of illumos. In that case, neither method really affects them, because they will just be reaching in and taking out the files they want (HEAD SHA will not really matter to them). Once we reach the goal of independant files not tethered to any implementation, this whole discussion becomes moot, because illumos will no longer be merged in.

I disagree with this. As an example, Delphix may or may not start to merge in OpenZFS into our internal DxOS tree. We haven't really discussed in detail if we actually want to start to use OpenZFS as our "upstream" (maybe in addition to illumos), but with a merge strategy that is a possibility; with a rebase strategy that is practially impossible because we can't simply "fetch and merge". In that case, DxOS would be a downstream consumer of OpenZFS, pulling code directly from the OpenZFS tree; we would not be "reaching in and taking out the files" that we needed.

**Pull request merged**
