### PR TITLE
3746 ZRLs are racy

### PR DESCRIPTION
**Pull request by youzhongyang**
Please see https://www.illumos.org/issues/3746 for how I reproduced the issue and tested this fix.

Thanks,

### CODE REVIEW

**Comment by dankimmel** [comment]
@zettabot go

**Comment by bprotopopov** [comment]
LGTM

**Comment by ahrens** [comment]
@pzakha Can you take a look? This seems similar to DLPX-45338 which you recently fixed at Delphix.

**Comment by youzhongyang** [comment]
I think the lint error is fixed, how can I request auto-build-and-test?

**Comment by ahrens** [comment]
@zettabot go

**Comment by pzakha** [comment]
LGTM, we have a very similar fix that we did recently at Delphix:

```C
void
zrl_add_impl(zrlock_t *zrl, const char *zc)
{
	uint32_t n = (uint32_t)zrl->zr_refcount;

	for (;;) {
		if (n == ZRL_LOCKED) {
			mutex_enter(&zrl->zr_mtx);
			while (zrl->zr_refcount == ZRL_LOCKED)
				cv_wait(&zrl->zr_cv, &zrl->zr_mtx);
			mutex_exit(&zrl->zr_mtx);
			n = (uint32_t)zrl->zr_refcount;
		} else {
			uint32_t cas = atomic_cas_32(
			    (uint32_t *)&zrl->zr_refcount, n, n + 1);
			if (cas == n) {
				ASSERT3S((int32_t)n, >=, 0);
#ifdef	ZFS_DEBUG
				if (zrl->zr_owner == curthread) {
					DTRACE_PROBE2(zrlock__reentry,
					    zrlock_t *, zrl, uint32_t, n);
				}
				zrl->zr_owner = curthread;
				zrl->zr_caller = zc;
#endif
				return;
			}
			n = cas;
		}
	}
}
```

**Pull request closed without merging**
