### PR TITLE
7512 Simplify the Makefiles in zfstest

### PR DESCRIPTION
**Pull request by jwk404**
Reviewed by: Dan Kimmel <dan.kimmel@delphix.com>
Reviewed by: Matthew Ahrens <mahrens@delphix.com>

### CODE REVIEW

**Comment by ahrens** [comment]
@zettabot go

**Comment by jwk404** [comment]
@zettabot go

**Comment by jwk404** [comment]
@zettabot go

**Comment by ikozhukhov** [comment]
i can see core dump of zloop, but i'm not sure it related to updates from illumos
can we try check it again?

**Comment by dankimmel** [comment]
@ikozhukhov: the zloop failure in `dmu_tx_willuse_space ` is a known bug. I don't think it's related to the new stuff pulled in from illumos.

**Comment by jwk404** [comment]
@zettabot go

**Pull request closed without merging**
