### PR TITLE
7816 remove static unused variable in zfs_vfsops.c

### PR DESCRIPTION
**Pull request by ikozhukhov**
Reviewed by: Matt Ahrens <mahrens@delphix.com>

issue found by gcc6

### CODE REVIEW

**Comment by ahrens** [comment]
@zettabot go

**Comment by ikozhukhov** [comment]
i want to add:
Reviewed by: Andy Stormont <astormont@racktopsystems.com>
but i need push force update.
when i can to do it?
have to wait a build/tests reports or in anytime?

**Comment by ahrens** [comment]
@ikozhukhov I think it's safe to do the force-push at any time.

**Comment by ikozhukhov** [comment]
thanks, pushed

**Comment by ahrens** [comment]
@zettabot go

**Pull request closed without merging**
