### PR TITLE
9626 move 'static xuio_stats_t xuio_stats' to file where it use

### PR DESCRIPTION
**Pull request by ikozhukhov**
it is part of another changes for reduce of gcc warnings

### CODE REVIEW

**Comment by ikozhukhov** [comment]
i have no found the reason why it failed.
based on logs with zfs tests i can see:
Test: /opt/zfs-tests/tests/functional/pool_checkpoint/checkpoint_big_rewind (run as root) [05:40] [PASS]
Cannot contact i-08feb8d6a44bfffce: java.lang.InterruptedException
Test: /opt/zfs-tests/tests/functional/pool_checkpoint/checkpoint_capacity (run as root) [02:39] [PASS]

but tests still works after that and finished with line:
Test: /opt/zfs-tests/tests/functional/removal/removal_with_dedup (run as root) [00:02] [PASS]
Test: /opt/zfs-tests/tests/functional/removal/removal_with_export (run as root) [00:25] [FAIL]
Sending interrupt signal to process
After 10s process did not stop

can someone point to me to issue with this PR?

**Comment by ikozhukhov** [comment]
@yuripv could you please send me email with your correct ID for Reviewed by: field.

**Comment by ikozhukhov** [comment]
@ahrens can I RTI this patch?

**Comment by ahrens** [comment]
@ikozhukhov You may.  FYI, advocates will probably ask about the test failures.

**Comment by ikozhukhov** [comment]
integrated by: https://github.com/illumos/illumos-gate/commit/857c96d257470e097e846ab8886580991b329c32

**Pull request closed without merging**
