### PR TITLE
Merge

### PR DESCRIPTION
**Pull request by ikozhukhov**

### CODE REVIEW

**Comment by ikozhukhov** [comment]
please @zettabot go

**Comment by ahrens** [comment]
@zettabot go

**Comment by ikozhukhov** [comment]
zpool failed - but it is illumos merge - i'm not sure it related.
@ahrens - can you take a look?

**Comment by ahrens** [comment]
Yeah, we'll ignore the zloop failure.  Still waiting for zfstest to complete.

**Pull request merged**
